-- #107: the twenty current profiles are generated by tools/gen-profiles.js from
-- tools/profile-template.yml. This suite applies the generator's rules in Lua
-- and compares the result with the files in profiles/, so a template edit that
-- was not regenerated - or a generated file somebody edited by hand - fails
-- here instead of shipping one icon with a different screen than the others.
--
-- The rules are the four of the generator's header comment. Two
-- implementations of a transformation this small are cheaper than a Lua
-- generator the JS one would have to shell out to, and they check each other:
-- the files on disk are the JS output, and they have to equal the Lua output.

local h = require "helpers"
local profiles = require "profiles"

local T = {}

local function dirname(path)
  return (path or ""):match("^(.*)[/\\][^/\\]*$")
end

local tests_dir = SCRIPT_DIR or dirname(arg and arg[0]) or "tests"
local edge_dir = tests_dir .. "/.."

local function read(path)
  if host and host.readfile then
    return host.readfile(path)
  end
  local file = io.open(path, "r")
  if not file then
    return nil
  end
  local text = file:read("a")
  file:close()
  return text
end

local function list(dir)
  local names = {}
  if host and host.listdir then
    for _, name in ipairs(host.listdir(dir)) do
      names[#names + 1] = name
    end
  elseif io.popen then
    local pipe = io.popen('ls "' .. dir .. '"')
    if pipe then
      for name in pipe:lines() do
        names[#names + 1] = name
      end
      pipe:close()
    end
  end
  table.sort(names)
  return names
end

local function lf(text)
  return ((text or ""):gsub("\r\n", "\n"))
end

local TEMPLATE = lf(read(edge_dir .. "/tools/profile-template.yml"))

--- pc.v2 -> pc-v2.yml, pc-tv-battery.v2 -> pc-tv-battery-v2.yml
local function file_name(name)
  return (name:gsub("%.v(%d+)$", "-v%1")) .. ".yml"
end

local function header(style, battery)
  return table.concat({
    "# GENERATED by tools/gen-profiles.js from tools/profile-template.yml - do not edit.",
    "# Change the template and run `bun tools/gen-profiles.js`; tests/profilegen_test.lua",
    "# fails while this file differs from what the template makes.",
    "# iconStyle: " .. style .. " · battery component: " .. (battery and "yes" or "no"),
  }, "\n") .. "\n"
end

local function replace_once(text, placeholder, value)
  local first = text:find(placeholder, 1, true)
  assert(first, "the template has no " .. placeholder)
  assert(not text:find(placeholder, first + 1, true), "the template has " .. placeholder .. " twice")
  return text:sub(1, first - 1) .. value .. text:sub(first + #placeholder)
end

--- The generator's rules (tools/gen-profiles.js `render`).
local function render(style, battery)
  -- The same pieces JS `split("\n")` makes: appending one "\n" and taking every
  -- "<line>\n" also yields the empty piece after a trailing newline.
  local lines = {}
  for line in (TEMPLATE .. "\n"):gmatch("([^\n]*)\n") do
    lines[#lines + 1] = line
  end
  local first
  for i, line in ipairs(lines) do
    if line:sub(1, 5) == "name:" then
      first = i
      break
    end
  end
  assert(first, "the template has no name: line")
  local out, in_battery = {}, false
  for i = first, #lines do
    local line = lines[i]
    if line == "# @battery-begin" then
      in_battery = true
    elseif line == "# @battery-end" then
      in_battery = false
    elseif not in_battery or battery then
      out[#out + 1] = line
    end
  end
  local body = table.concat(out, "\n")
  body = replace_once(body, "__NAME__", profiles.for_style(style, battery))
  body = replace_once(body, "__CATEGORY__", profiles.CATEGORIES[style])
  return header(style, battery) .. body
end

function T.test_the_template_exists_outside_the_package()
  -- profiles/ is packaged whole, so the template must not live there.
  h.assert_true(TEMPLATE ~= "", "tools/profile-template.yml is missing")
  h.assert_contains(TEMPLATE, "name: __NAME__")
  h.assert_contains(TEMPLATE, "- name: __CATEGORY__")
  h.assert_contains(TEMPLATE, "# @battery-begin")
  h.assert_contains(TEMPLATE, "# @battery-end")
  for _, name in ipairs(list(edge_dir .. "/profiles")) do
    h.assert_true(name:find("template", 1, true) == nil, "profiles/" .. name .. " looks like a template")
  end
end

function T.test_every_current_profile_is_the_template_rendered()
  local checked = 0
  for _, battery in ipairs({ false, true }) do
    for _, style in ipairs(profiles.STYLES) do
      local name = profiles.for_style(style, battery)
      local path = edge_dir .. "/profiles/" .. file_name(name)
      local on_disk = read(path)
      h.assert_true(on_disk ~= nil, "profiles/" .. file_name(name) .. " is missing - run bun tools/gen-profiles.js")
      h.assert_true(lf(on_disk) == render(style, battery),
        "profiles/" .. file_name(name) .. " is stale or was edited by hand - run bun tools/gen-profiles.js")
      checked = checked + 1
    end
  end
  h.assert_equal(checked, 20)
end

function T.test_only_the_battery_profiles_carry_the_battery_component()
  for _, battery in ipairs({ false, true }) do
    for _, style in ipairs(profiles.STYLES) do
      local text = render(style, battery)
      local has = text:find("\n  - id: battery\n", 1, true) ~= nil
      h.assert_equal(has, battery, profiles.for_style(style, battery) .. " battery component")
      if battery then
        h.assert_contains(text, "      - id: battery\n")
        h.assert_contains(text, "      - id: powerSource\n")
      end
      h.assert_true(text:find("@battery", 1, true) == nil, "a marker line leaked into the output")
    end
  end
end

function T.test_every_generated_profile_has_one_name_and_one_category()
  for _, battery in ipairs({ false, true }) do
    for _, style in ipairs(profiles.STYLES) do
      local text = render(style, battery)
      h.assert_contains(text, "\nname: " .. profiles.for_style(style, battery) .. "\n")
      h.assert_contains(text, "\n      - name: " .. profiles.CATEGORIES[style] .. "\n")
      h.assert_true(text:find("__", 1, true) == nil, "a placeholder is left in " .. style)
    end
  end
end

function T.test_no_stray_file_of_the_current_generation()
  -- A `-v2.yml` that the generator does not write is a style that was dropped
  -- from the list but not from the disk, and the packager would ship it.
  local wanted = {}
  for _, battery in ipairs({ false, true }) do
    for _, style in ipairs(profiles.STYLES) do
      wanted[file_name(profiles.for_style(style, battery))] = true
    end
  end
  local suffix = "-v" .. profiles.VERSION .. ".yml"
  for _, name in ipairs(list(edge_dir .. "/profiles")) do
    if name:sub(-#suffix) == suffix then
      h.assert_true(wanted[name] == true, "profiles/" .. name .. " is not generated by tools/gen-profiles.js")
    end
  end
end

function T.test_the_generator_knows_the_same_styles_and_categories()
  -- tools/gen-profiles.js carries its own copy of the list. Read it back out
  -- of the source rather than trusting the two to agree.
  local source = lf(read(edge_dir .. "/tools/gen-profiles.js"))
  local seen = {}
  for style, category in source:gmatch("%[%s*'(%a+)',%s*'(%a+)'%s*%]") do
    seen[#seen + 1] = style
    h.assert_equal(category, profiles.CATEGORIES[style], "gen-profiles.js category of " .. style)
  end
  h.assert_deep_equal(seen, profiles.STYLES, "gen-profiles.js STYLES")
  h.assert_contains(source, "const VERSION = " .. profiles.VERSION .. ";")
end

return T
