-- #107: the twenty current profiles are generated by tools/gen-profiles.js from
-- tools/profile-template.yml, and CI's `npm run check-profiles` fails when a
-- file on disk is not what the generator writes. This suite does not repeat
-- the generator: it checks what the packager ships (exactly the profiles the
-- driver can name, nothing stray, no template), that the driver and the
-- generator agree on the styles, and the rules the current files must keep
-- whatever the template says.

local h = require "helpers"
local profiles = require "profiles"

local T = {}

local function dirname(path)
  return (path or ""):match("^(.*)[/\\][^/\\]*$")
end

local tests_dir = SCRIPT_DIR or dirname(arg and arg[0]) or "tests"
local edge_dir = tests_dir .. "/.."

local function read(path)
  if host and host.readfile then
    return host.readfile(path)
  end
  local file = io.open(path, "r")
  if not file then
    return nil
  end
  local text = file:read("a")
  file:close()
  return text
end

local function list(dir)
  local names = {}
  if host and host.listdir then
    for _, name in ipairs(host.listdir(dir)) do
      names[#names + 1] = name
    end
  elseif io.popen then
    local pipe = io.popen('ls "' .. dir .. '"')
    if pipe then
      for name in pipe:lines() do
        names[#names + 1] = name
      end
      pipe:close()
    end
  end
  table.sort(names)
  return names
end

local function lf(text)
  return ((text or ""):gsub("\r\n", "\n"))
end

--- The file a profile name is packaged as: the frozen v1 files are
--- `pc.yml`/`pc-tv.yml`, later generations `pc-v9.yml`/`pc-tv-battery-v9.yml`.
local function file_name(name)
  if name:match("%.v1$") then
    return (name:gsub("%.v1$", "")) .. ".yml"
  end
  return (name:gsub("%.v(%d+)$", "-v%1")) .. ".yml"
end

local function profile_text(name)
  return lf(read(edge_dir .. "/profiles/" .. file_name(name)))
end

-- The package (`profiles/` is uploaded whole, and the upload limit is 655360
-- bytes): every shipped name the driver knows - the ten frozen v1 files and
-- the twenty current ones, not the Dev-only v2 to v8 (UNSHIPPED_VERSIONS) -
-- each declaring its own name, and nothing else (a style dropped from the
-- list but not from the disk, the template, or #123's removed pc-app.yml
-- would otherwise ship as a profile).
function T.test_the_package_is_exactly_the_shipped_profiles()
  local want = {}
  for _, name in ipairs(profiles.KNOWN) do
    if profiles.is_shipped(name) then
      want[file_name(name)] = name
    else
      -- A development device on an unshipped generation still migrates.
      h.assert_true(profiles.is_current(profiles.migration_for(name)), name .. " must still migrate")
    end
  end
  local on_disk = {}
  for _, f in ipairs(list(edge_dir .. "/profiles")) do
    on_disk[f] = true
    h.assert_true(want[f] ~= nil, "profiles/" .. f .. " is not a profile the driver ships")
  end
  for f, name in pairs(want) do
    h.assert_true(on_disk[f] == true, "profiles/" .. f .. " is missing")
    h.assert_contains(profile_text(name), "\nname: " .. name .. "\n", f .. " declares its name")
  end
  h.assert_true(read(edge_dir .. "/tools/profile-template.yml") ~= nil, "the template lives in tools/")
end

function T.test_the_generator_knows_the_same_styles_and_categories()
  -- tools/gen-profiles.js carries its own copy of the list. Read it back out
  -- of the source rather than trusting the two to agree.
  local source = lf(read(edge_dir .. "/tools/gen-profiles.js"))
  local seen = {}
  for style, category in source:gmatch("%[%s*'(%a+)',%s*'(%a+)'%s*%]") do
    seen[#seen + 1] = style
    h.assert_equal(category, profiles.CATEGORIES[style], "gen-profiles.js category of " .. style)
  end
  h.assert_deep_equal(seen, profiles.STYLES, "gen-profiles.js STYLES")
  h.assert_contains(source, "const VERSION = " .. profiles.VERSION .. ";")
end

--- The capability ids of one component of a profile, in order.
local function component_capabilities(text, component)
  local block = text:match("\n  %- id: " .. component .. "\n(.-)\n  %- id: ")
    or text:match("\n  %- id: " .. component .. "\n(.-)\npreferences:")
  local ids = {}
  for id in (block or ""):gmatch("\n      %- id: ([%w%.]+)") do
    ids[#ids + 1] = id
  end
  return ids
end

-- What every current profile must keep, whatever the template says:
--   * its style's category (the icon the app shows);
--   * the battery component exactly on the battery half (#116);
--   * the media group in main right after the edge-v1.0 cards, in the order
--     of media-notify.md §15 "UI 구성", and pcToast closing main;
--   * nothing that reads aloud: the app labels `notification` "텍스트 표시"
--     and `speechSynthesis` "음성 합성" and a device configuration cannot
--     override that; read-aloud and pcMessage were dropped for pcToast.
function T.test_every_current_profile_keeps_the_layout_rules()
  local media_group = { "audioTrackData", "mediaPlayback", "mediaTrackControl", "audioVolume", "audioMute" }
  for _, battery in ipairs({ false, true }) do
    for _, style in ipairs(profiles.STYLES) do
      local name = profiles.for_style(style, battery)
      local text = profile_text(name)
      h.assert_contains(text, "\n      - name: " .. profiles.CATEGORIES[style] .. "\n", name .. " category")
      h.assert_equal(text:find("\n  - id: battery\n", 1, true) ~= nil, battery, name .. " battery component")
      h.assert_nil(text:find("__", 1, true), name .. " has a placeholder left")

      local main = component_capabilities(text, "main")
      local at
      for i, id in ipairs(main) do
        if id == "numbersystem53811.pcversion" then
          at = i
        end
      end
      h.assert_true(at ~= nil, name .. " has no pcVersion card")
      for k, id in ipairs(media_group) do
        h.assert_equal(main[at + k], id, name .. " media group position " .. k)
      end
      h.assert_deep_equal({ main[at + 6], main[at + 7] }, {
        "numbersystem53811.pcpreset", "numbersystem53811.pctoast",
      }, name .. " closes main with presets, toast")
      h.assert_equal(#main, at + 7, name .. ": pcToast is the last capability of main")
      -- #123: the watch card is a component of its own, its one capability.
      h.assert_deep_equal(component_capabilities(text, "apps"), { "numbersystem53811.pcwatch" },
        name .. " watch card")
      h.assert_contains(text, "\n  - id: apps\n    label: 감시 목록\n", name .. " watch card label")

      h.assert_nil(text:find("\n      - id: notification\n", 1, true), name .. " still lists notification")
      h.assert_nil(text:find("\n      - id: speechSynthesis\n", 1, true), name .. " still lists speechSynthesis")
      h.assert_nil(text:find("pcmessage", 1, true), name .. " still lists pcMessage")
    end
  end
end

return T
