-- Profile names and the migration between their versions (design doc §6.6).
--
-- Measured on the hub (#79): a device's screen definition is generated from
-- the capability presentations *at device-creation time* and is never
-- regenerated. Re-publishing the same profile name (pc.v1) picked up new
-- preferences but kept the old detail view; only moving the device to a
-- profile with a **new name** regenerates it.
--
-- So every presentation change bumps the profile version: a new set of
-- profile files with `name: pc.vN`, the older files kept in the package
-- (existing devices still reference them until they are moved), and this
-- module moves each device over on its first `init` after the update.
--
-- #90: at the first channel release the numbering was reset to `pc.v1`.
--
-- #100: the icon. The app draws a device's icon from its profile's category,
-- `Others` offers no icon choice, and a category is fixed per profile - so the
-- `iconStyle` preference is served by one profile per style, identical except
-- for `name` and the category (`pc-monitor.vN`, …). All of them are "current"
-- (`CURRENT`): a device on any of them is where it belongs and `ensure` never
-- moves it. `apply_style` moves a device between them when the preference and
-- the profile disagree.
--
-- #107: `pc.v2`. The screen gained the standard audio and media capabilities
-- (and, with the rest of edge-v1.1.0, `pcPreset`, `pcActivity`, the `awake`
-- component and the notification capabilities), so every name moved to v2 and
-- every v1 name went into `KNOWN`. `migration_for` keeps the style it reads off
-- the old name, so a device on `pc-monitor.v1` lands on `pc-monitor.v2`.
--
-- #107: and a second axis. A laptop gets the standard `battery`/`powerSource`
-- capabilities on a component of their own (#116), but a desktop must not
-- carry an empty battery card, so every style exists with and without that
-- component: `pc-<style>.v2` and `pc-<style>-battery.v2` (`pc.v2` /
-- `pc-battery.v2` for the default style). Twenty profiles, none of them written
-- by hand - they are generated by tools/gen-profiles.js from
-- tools/profile-template.yml, and tests/profilegen_test.lua fails while a file
-- on disk differs from what the template makes. `apply_style` keeps the
-- battery half of the name, `apply_battery` (#116) keeps the style half.
--
-- `pc.v3`: the standard `notification` / `speechSynthesis` rows gave way to our
-- own `pcMessage` ("PC에 메시지 보내기" / "PC에서 소리내어 읽기" - the app
-- labels a standard capability in Samsung's words and a device configuration
-- cannot override them). A different capability list is a different screen,
-- so every name moved to v3; the twenty v2 names went into `KNOWN` after the
-- ten v1 ones, their files stay in the package, frozen, and a v2 device lands
-- on the v3 of the same style and the same battery half.
--
-- `pc.v4`: read-aloud was dropped, and `pcMessage` (send + speak) gave way to
-- `pcNotify` with the one command "PC에 메시지 보내기". A new capability id is
-- a new capability list, so every name moved to v4. Neither v2 nor v3 was ever
-- published (`UNSHIPPED_VERSIONS`): their names stay in `KNOWN` so a
-- development device on one still lands on the v4 of its style and battery
-- half, but their files are gone from the package.
--
-- `pc.v5`: `pcNotify` gave way to `pcToast`, the same command plus a
-- `lastMessage` attribute the text row is bound to (a row bound to no
-- attribute spun and ended in "네트워크 오류"). A new id, so a new name again;
-- v4 never left the Dev channel either and joins `UNSHIPPED_VERSIONS`.
--
-- `pc.v6` (#123): the kind-based `pcActivity` gave way to `pcApps`, one
-- summary row; each watched app became a child device of its own on
-- `pc-app.v1` (`APP`), which is not one of the PC's names at all - never
-- current, never known, never migrated. v5 joins `UNSHIPPED_VERSIONS`.
--
-- Everything here is pure except `remember`, `ensure`, `apply_style`,
-- `apply_battery` and `remove_legacy_child`, which touch the device, and all of
-- them are guarded: a hub that refuses `try_update_metadata` or
-- `try_delete_device` must not take the lifecycle handler down with it.

local fields = require "device.fields"

local profiles = {}

-- The profile generation every current name carries (`pc.v6`, …).
profiles.VERSION = 6

-- #123: the app child device's profile (profiles/pc-app.yml). Not a PC
-- profile: `ensure`, `apply_style` and `apply_battery` never see a child, and
-- the name is in neither `CURRENT` nor `KNOWN`.
profiles.APP = "pc-app.v1"
profiles.APP_PREFIX = "pc-app."

-- #100: the `iconStyle` preference, whose default is served by `PC` itself.
profiles.DEFAULT_STYLE = "others"

-- The styles in the order the preference lists them, and the category each
-- profile file declares - what the app picks the icon from. Documentation as
-- much as data: the tests check both against the template and the files, and
-- tools/gen-profiles.js carries the same two lists.
profiles.STYLES = {
  "others", "monitor", "switch", "plug", "tv",
  "projector", "network", "hub", "theater", "remote",
}
profiles.CATEGORIES = {
  others = "Others",
  monitor = "SmartMonitor",
  switch = "Switch",
  plug = "SmartPlug",
  tv = "Television",
  projector = "Projector",
  network = "Networking",
  hub = "Hub",
  theater = "HomeTheater",
  remote = "RemoteController",
}

--- The profile name for one style and battery choice at `version`:
--- `pc.v6`, `pc-tv.v6`, `pc-battery.v6`, `pc-tv-battery.v6`.
function profiles.name_for(style, battery, version)
  local name = "pc"
  if style ~= nil and style ~= profiles.DEFAULT_STYLE then
    name = name .. "-" .. style
  end
  if battery == true then
    name = name .. "-battery"
  end
  return string.format("%s.v%d", name, version or profiles.VERSION)
end

-- What new devices are created with: the default style, no battery. A laptop
-- moves to `pc-battery.v6` once its status says so (#116).
profiles.PC = profiles.name_for(profiles.DEFAULT_STYLE, false)

-- #107: the battery twin of `PC`.
profiles.BATTERY = profiles.name_for(profiles.DEFAULT_STYLE, true)

-- Every other style and the profile that carries its category, without and
-- with the battery component (#116). The files are generated.
profiles.VARIANTS = {}
profiles.BATTERY_VARIANTS = {}
for _, style in ipairs(profiles.STYLES) do
  if style ~= profiles.DEFAULT_STYLE then
    profiles.VARIANTS[style] = profiles.name_for(style, false)
    profiles.BATTERY_VARIANTS[style] = profiles.name_for(style, true)
  end
end

-- Every name a device may sit on without being migrated: `PC`, `BATTERY` and
-- each variant of both. A set, `CURRENT[name] == true`.
profiles.CURRENT = { [profiles.PC] = true, [profiles.BATTERY] = true }
for _, name in pairs(profiles.VARIANTS) do
  profiles.CURRENT[name] = true
end
for _, name in pairs(profiles.BATTERY_VARIANTS) do
  profiles.CURRENT[name] = true
end

-- Every profile name this driver has ever shipped, oldest first. A name that
-- is not in here belongs to another driver, or to a version newer than this
-- one, and is left alone. #107: the ten v1 names (the default and the nine
-- icon variants of #100), then twenty names per later generation (every style
-- with and without the battery, #116): v2, v3 and the twenty current ones.
profiles.KNOWN = {}
for _, style in ipairs(profiles.STYLES) do
  profiles.KNOWN[#profiles.KNOWN + 1] = profiles.name_for(style, false, 1)
end
for version = 2, profiles.VERSION do
  for _, battery in ipairs({ false, true }) do
    for _, style in ipairs(profiles.STYLES) do
      profiles.KNOWN[#profiles.KNOWN + 1] = profiles.name_for(style, battery, version)
    end
  end
end

-- Generations that were never published on the public channel and are not
-- in the package. Their names stay in KNOWN so a development device still on
-- one migrates, but the files are dropped: SmartThings refuses a driver whose
-- files add up to more than 655360 bytes, and each generation of twenty
-- profiles is about 165 KB (measured 2026-09-30 when v1+v2+v3 reached 666 KB).
-- v2 lived only on the Dev channel (edge-v1.1.0 development), and so did v3
-- (pcMessage, with read-aloud), v4 (pcNotify, no attribute) and v5 (pcToast
-- with the kind-based pcActivity, #123).
profiles.UNSHIPPED_VERSIONS = { [2] = true, [3] = true, [4] = true, [5] = true }

--- True when the package carries a file for this profile name.
function profiles.is_shipped(name)
  local version = tonumber(tostring(name or ""):match("%.v(%d+)$"))
  return version ~= nil and not profiles.UNSHIPPED_VERSIONS[version]
end

-- The profile name is written here at creation time and after a migration,
-- because `device.profile` does not always carry a name (see `name_of`).

-- #116: whether the last settled status said this PC has a battery. Persisted,
-- so a later migration (v1 -> v5) lands a laptop straight on its battery
-- profile instead of taking the detour through the plain one.

-- What a device with neither a name nor the field is assumed to be on: the
-- oldest name this driver ever created a device with.
profiles.LEGACY = "pc.v1"

-- #81: the display child device is gone. Its profiles (`pc-display.vN`) are no
-- longer in the package, so a child left on a hub from an older driver has
-- nothing to render and is deleted on the next init.
--
-- Only a development hub can still carry such a child, since #81 predates the
-- first channel release (#90). Kept anyway: the check is one pure comparison
-- per device per driver run and the author's own hub is such a hub.
profiles.DISPLAY_PREFIX = "pc-display"
-- The key the display child was created with (display.lua before #81).
profiles.LEGACY_CHILD_KEY = "display"

local function logger()
  local ok, log = pcall(require, "log")
  if ok then
    return log
  end
  local noop = function() end
  return { trace = noop, debug = noop, info = noop, warn = noop, error = noop }
end

--------------------------------------------------------------------------------
-- pure
--------------------------------------------------------------------------------

--- The profile a device is created with now.
function profiles.current()
  return profiles.PC
end

--- Every profile name this driver has shipped.
function profiles.known()
  return profiles.KNOWN
end

--- #100: true when `name` is one of the profiles a device is created on or
--- switched between now - `PC` or any variant, with or without the battery.
function profiles.is_current(name)
  if type(name) ~= "string" or name == "" then
    return false
  end
  return name == profiles.PC or profiles.CURRENT[name] == true
end

--- #100/#116: the profile an `iconStyle` value asks for, with or without the
--- battery component. Anything that is not a known style (nil, a typo, a value
--- a newer driver added) is the default.
function profiles.for_style(style, battery)
  if battery == true then
    return profiles.BATTERY_VARIANTS[style] or profiles.BATTERY
  end
  return profiles.VARIANTS[style] or profiles.PC
end

--- #100: the `iconStyle` a current profile name stands for, or nil for a name
--- that is not current (older, foreign, or none).
function profiles.style_of(name)
  if type(name) ~= "string" then
    return nil
  end
  if name == profiles.PC or name == profiles.BATTERY then
    return profiles.DEFAULT_STYLE
  end
  for style, variant in pairs(profiles.VARIANTS) do
    if variant == name or profiles.BATTERY_VARIANTS[style] == name then
      return style
    end
  end
  return nil
end

--- #116: true when a current profile name is one of the battery variants,
--- false for the plain ones, nil for a name that is not current.
function profiles.battery_of(name)
  if not profiles.is_current(name) then
    return nil
  end
  return name:match("%-battery%.v%d+$") ~= nil
end

--- The style an OLDER name of this driver carried: `pc-<style>[-battery].vN`
--- with a style that still exists, else the default. Pure pattern reading,
--- because a superseded name is by definition no longer in `VARIANTS`.
local function style_in_name(name)
  local base = name:gsub("%-battery(%.v%d+)$", "%1")
  local style = base:match("^pc%-(%a+)%.v%d+$")
  if style and profiles.VARIANTS[style] then
    return style
  end
  return profiles.DEFAULT_STYLE
end

--- The profile `device_profile_name` has to move to, or nil.
--
-- nil covers all three "do nothing" cases: already current (any variant,
-- #100), not a name this driver ever used (foreign device, or a version from
-- the future), and no name at all. A `pc-display.vN` name is not ours to
-- migrate either: #81 removed that series, and such a device is deleted
-- instead (`is_legacy_child`). A known older name keeps its style, and a
-- `-battery` name (v2 on) keeps its battery half.
-- @param battery #107: whether the target is the battery variant. The v1 names
--   never had one, so the caller says, and "no" until a status has said
--   otherwise. A v2 `-battery` name already says "yes" and goes to a battery
--   profile whatever the caller passes: the device got there on two statuses
--   that agreed (#116), which is better evidence than a field a single odd
--   status may not have written.
function profiles.migration_for(device_profile_name, battery)
  if type(device_profile_name) ~= "string" or device_profile_name == "" then
    return nil
  end
  if profiles.is_current(device_profile_name) then
    return nil
  end
  for _, known in ipairs(profiles.known()) do
    if device_profile_name == known then
      local on_battery = battery == true
        or device_profile_name:match("%-battery%.v%d+$") ~= nil
      return profiles.for_style(style_in_name(device_profile_name), on_battery)
    end
  end
  return nil
end


--- #123: true when `name` is the app child's profile (any version of it).
function profiles.is_app_profile(name)
  return type(name) == "string" and name:sub(1, #profiles.APP_PREFIX) == profiles.APP_PREFIX
end

--- #81: true when `device` is a leftover display child of an older driver.
--
-- Two independent marks, because a hub may only carry one of them: the
-- `parent_assigned_child_key` the display child was created with ("display",
-- `LEGACY_CHILD_KEY`), and a profile name from the removed `pc-display`
-- series. Pure, so the decision is testable without a hub.
-- #123: any other child key is an app child of this driver (apps.lua), which
-- is very much wanted - before #123 every child key meant "leftover".
function profiles.is_legacy_child(device)
  if type(device) ~= "table" then
    return false
  end
  local name = profiles.name_of(device)
  if type(name) == "string"
      and name:sub(1, #profiles.DISPLAY_PREFIX) == profiles.DISPLAY_PREFIX then
    return true
  end
  return device.parent_assigned_child_key == profiles.LEGACY_CHILD_KEY
    and not profiles.is_app_profile(name)
end

--------------------------------------------------------------------------------
-- reading the name off a device
--------------------------------------------------------------------------------

local function stored_name(device)
  if type(device) ~= "table" or type(device.get_field) ~= "function" then
    return nil
  end
  local value = fields.get(device, fields.PROFILE_NAME)
  if type(value) == "string" and value ~= "" then
    return value
  end
  return nil
end

--- The profile name of `device`.
--
-- The Edge API exposes `device.profile` as a table of `id` and `components`;
-- the *name* is there on some firmwares only, so it wins when present and the
-- field written at creation time (and after every migration) is the fallback.
-- A device with neither predates #79 and is therefore on v1.
function profiles.name_of(device)
  local profile = (device or {}).profile
  if type(profile) == "table" and type(profile.name) == "string" and profile.name ~= "" then
    return profile.name
  end
  if type(profile) == "string" and profile ~= "" then
    return profile
  end
  return stored_name(device) or profiles.LEGACY
end

--------------------------------------------------------------------------------
-- driver glue
--------------------------------------------------------------------------------

--- Record that `device` is on the current profile, so the next driver version
--- can tell which version it has to move it from.
function profiles.remember(device, name)
  if type(device) ~= "table" or type(device.set_field) ~= "function" then
    return nil
  end
  name = name or profiles.current()
  fields.set(device, fields.PROFILE_NAME, name)
  return name
end

-- Devices this driver run has already looked at. One attempt per device per
-- driver lifetime: `added` and `init` both call `ensure`, and a hub that
-- refuses the update must not be asked again in a loop.
local attempted = {}

-- #100: the loop guard of `apply_style`, two maps per driver run.
--
-- `switched` is the profile this run last moved each device to. It stands in
-- for `name_of` afterwards: the switch itself fires `infoChanged` again, and on
-- a hub that is slow to (or never does) put the new name on `device.profile`,
-- `name_of` would still read the old one and ask for the same switch again,
-- and again. #107: `ensure` writes it too.
--
-- `refused` is the target the hub last turned down. The same preference is
-- not asked for twice in one run; a different value, or the next driver start,
-- asks again.
local switched = {}
local refused = {}

local function attempt_key(device)
  local id = device.id
  if type(id) == "string" and id ~= "" then
    return id
  end
  return device
end

--- The profile name this driver run believes `device` is on: the one it last
--- moved it to, else what the device says (`name_of`).
function profiles.current_name(device)
  if type(device) ~= "table" then
    return nil
  end
  return switched[attempt_key(device)] or profiles.name_of(device)
end

--- Move `device` onto the current profile if it is due (§6.6).
--
-- Returns the new profile name, or nil when nothing was done. Called from
-- `init` and `added`; only the first call per device does anything.
function profiles.ensure(device)
  if type(device) ~= "table" then
    return nil
  end
  local key = attempt_key(device)
  if attempted[key] then
    return nil
  end
  attempted[key] = true

  local name = profiles.name_of(device)
  -- #107: a v1 device lands on the current profile of its style. Whether it
  -- has a battery is only known once a status has said so (#116:
  -- `fields.HAS_BATTERY`, which a v1 device never wrote), so it lands on the plain
  -- one and the first statuses move a laptop on (`apply_battery`). A v2 device
  -- keeps its battery half (`migration_for`).
  local target = profiles.migration_for(name, profiles.has_battery(device))
  if not target then
    -- Nothing to do, but keep the field in step with reality when the device
    -- is already on a current profile (the default or a variant, #100).
    if profiles.is_current(name) then
      profiles.remember(device, name)
    end
    return nil
  end

  local ok, err = pcall(function()
    return device:try_update_metadata({ profile = target })
  end)
  if not ok then
    logger().warn(string.format("could not migrate %s to %s: %s",
      tostring(device.id), target, tostring(err)))
    return nil
  end
  profiles.remember(device, target)
  -- #107: from here on this run reads the new name, whatever the hub still
  -- reports on `device.profile` - an icon switch right after a migration must
  -- start from the new name, not from the old one it would refuse to touch.
  switched[key] = target
  logger().info(string.format("migrated %s to %s", tostring(device.id), target))
  return target
end

--- #100: move `device` onto the profile its `iconStyle` preference asks for.
--
-- Returns the new profile name, or nil when nothing was done. Called from
-- `infoChanged` (the user changed the preference) and from `init` (the driver
-- restarted between the preference changing and the switch landing).
--
-- Left alone: a device with no `iconStyle` at all (the preferences have not
-- arrived - it is not a request for the default), and a device that is not on
-- a current profile (foreign, or an older version that `ensure` moves first).
-- At most one `try_update_metadata` per device and target per driver run.
function profiles.apply_style(device)
  if type(device) ~= "table" then
    return nil
  end
  local style = (device.preferences or {}).iconStyle
  if style == nil then
    return nil
  end
  local key = attempt_key(device)
  local name = profiles.current_name(device)
  if not profiles.is_current(name) then
    return nil
  end
  -- #107: the icon changes, the battery component stays where it is.
  local target = profiles.for_style(style, profiles.battery_of(name))
  if name == target or refused[key] == target then
    return nil
  end

  local ok, err = pcall(function()
    return device:try_update_metadata({ profile = target })
  end)
  if not ok then
    refused[key] = target
    logger().warn(string.format("could not switch %s to %s: %s",
      tostring(device.id), target, tostring(err)))
    return nil
  end
  switched[key] = target
  refused[key] = nil
  profiles.remember(device, target)
  logger().info(string.format("switched %s from %s to %s (iconStyle %s)",
    tostring(device.id), name, target, tostring(style)))
  return target
end

-- #116: consecutive statuses that disagreed with the device's profile about
-- the battery, per device: `{ present = bool, count = n }`.
local battery_votes = {}

-- #116: how many statuses in a row have to say the same thing before the
-- device changes profile. One odd reading (a flaky `GetSystemPowerStatus`, a
-- service that restarted into its "no battery yet" placeholder) must not cost
-- the user a profile switch and a repaint each way.
profiles.BATTERY_VOTES = 2

--- #116: whether the last settled status said this PC has a battery (the
--- persisted `fields.HAS_BATTERY`), false when none has.
function profiles.has_battery(device)
  return fields.get(device, fields.HAS_BATTERY) == true
end

local function remember_battery(device, present)
  if profiles.has_battery(device) ~= present then
    fields.set(device, fields.HAS_BATTERY, present)
  end
end

--- #116: move `device` between the plain and the `-battery` profile of its
--- style when the status disagrees with the one it is on.
--
-- Returns the new profile name, or nil when nothing was done. Called after
-- every status (poll and push) with `status.battery.present`. Only after
-- `BATTERY_VOTES` consecutive statuses agree on the other answer does it ask
-- for the switch - one each way at most per real change. The style is the one
-- the current name carries (`iconStyle` is `apply_style`'s business), and a
-- device that is not on a current profile is left to `ensure`. The answer is
-- persisted (`fields.HAS_BATTERY`) so the next migration lands on the right side.
function profiles.apply_battery(device, present)
  if type(device) ~= "table" then
    return nil
  end
  present = present == true
  local key = attempt_key(device)
  local name = profiles.current_name(device)
  local on_battery = profiles.battery_of(name)
  if on_battery == nil then
    battery_votes[key] = nil
    return nil
  end
  if on_battery == present then
    battery_votes[key] = nil
    remember_battery(device, present)
    return nil
  end
  local votes = battery_votes[key]
  if votes and votes.present == present then
    votes.count = votes.count + 1
  else
    votes = { present = present, count = 1 }
    battery_votes[key] = votes
  end
  if votes.count < profiles.BATTERY_VOTES then
    return nil
  end
  local target = profiles.for_style(profiles.style_of(name), present)
  if refused[key] == target then
    return nil
  end
  local ok, err = pcall(function()
    return device:try_update_metadata({ profile = target })
  end)
  if not ok then
    refused[key] = target
    logger().warn(string.format("could not switch %s to %s: %s",
      tostring(device.id), target, tostring(err)))
    return nil
  end
  battery_votes[key] = nil
  switched[key] = target
  refused[key] = nil
  profiles.remember(device, target)
  remember_battery(device, present)
  logger().info(string.format("switched %s from %s to %s (battery %s)",
    tostring(device.id), name, target, present and "present" or "absent"))
  return target
end

-- Devices this driver run has already tried to delete (#81), for the same
-- reason `attempted` exists: `init` fires more than once per device.
local removed = {}

--- #81: delete a leftover display child, once per device per driver run.
--
-- Returns true when the delete was attempted. Both APIs are tried because
-- `try_delete_device` sits on the device on some firmwares and on the driver
-- on others, and neither may take the lifecycle handler down.
function profiles.remove_legacy_child(driver, device)
  if not profiles.is_legacy_child(device) then
    return false
  end
  local key = attempt_key(device)
  if removed[key] then
    return false
  end
  removed[key] = true

  logger().info("removing legacy display child " .. tostring(device.id))
  local ok = pcall(function() return device:try_delete_device() end)
  if not ok and driver then
    pcall(function() return driver:try_delete_device(device.id) end)
  end
  return true
end

--- Forget the one-attempt-per-device guards (tests only).
function profiles.reset()
  attempted = {}
  removed = {}
  switched = {}
  refused = {}
  battery_votes = {}
end

return profiles
