
-- Profile names and the migration between their versions (design doc §6.6).
--
-- A device's screen is fixed by the presentations at creation time; only a
-- profile with a new name regenerates it (platform notes "프로필과 화면 생성").
-- So every screen change bumps the generation (`VERSION`, `pc.vN`): the
-- older published files stay in the package for the devices still on them,
-- and `ensure` moves each device on its first `init` after the update.
--
-- Two axes inside a generation, twenty names, all of them current: the
-- `iconStyle` preference (the app draws the icon from the profile's category,
-- fixed per profile: `pc-monitor.vN`, …; `apply_style`), and the battery
-- component a desktop must not carry (`pc-battery.vN`, …; `apply_battery`).
-- The files are generated by tools/gen-profiles.js. A migration keeps the
-- style and the battery half the old name carries.
--
-- Everything here is pure except `remember`, `ensure`, `apply_style`,
-- `apply_battery`, `remove_child` and `remove_children`, which touch the
-- device or the driver, and all of them are guarded: a hub that refuses
-- `try_update_metadata` or `try_delete_device` must not take the lifecycle
-- handler down with it.

local fields = require "device.fields"

local profiles = {}

-- The profile generation every current name carries (`pc.v7`, …).
profiles.VERSION = 7

-- #100: the `iconStyle` preference, whose default is served by `PC` itself.
profiles.DEFAULT_STYLE = "others"

-- The styles in the order the preference lists them, and the category each
-- profile file declares - what the app picks the icon from. Documentation as
-- much as data: the tests check both against the template and the files, and
-- tools/gen-profiles.js carries the same two lists.
profiles.STYLES = {
  "others", "monitor", "switch", "plug", "tv",
  "projector", "network", "hub", "theater", "remote",
}
profiles.CATEGORIES = {
  others = "Others",
  monitor = "SmartMonitor",
  switch = "Switch",
  plug = "SmartPlug",
  tv = "Television",
  projector = "Projector",
  network = "Networking",
  hub = "Hub",
  theater = "HomeTheater",
  remote = "RemoteController",
}

--- The profile name for one style and battery choice at `version`:
--- `pc.v7`, `pc-tv.v7`, `pc-battery.v7`, `pc-tv-battery.v7`.
function profiles.name_for(style, battery, version)
  local name = "pc"
  if style ~= nil and style ~= profiles.DEFAULT_STYLE then
    name = name .. "-" .. style
  end
  if battery == true then
    name = name .. "-battery"
  end
  return string.format("%s.v%d", name, version or profiles.VERSION)
end

-- What new devices are created with: the default style, no battery. A laptop
-- moves to `pc-battery.v7` once its status says so (#116).
profiles.PC = profiles.name_for(profiles.DEFAULT_STYLE, false)

-- #107: the battery twin of `PC`.
profiles.BATTERY = profiles.name_for(profiles.DEFAULT_STYLE, true)

-- Every other style and the profile that carries its category, without and
-- with the battery component (#116). The files are generated.
profiles.VARIANTS = {}
profiles.BATTERY_VARIANTS = {}
for _, style in ipairs(profiles.STYLES) do
  if style ~= profiles.DEFAULT_STYLE then
    profiles.VARIANTS[style] = profiles.name_for(style, false)
    profiles.BATTERY_VARIANTS[style] = profiles.name_for(style, true)
  end
end

-- Every name a device may sit on without being migrated: `PC`, `BATTERY` and
-- each variant of both. A set, `CURRENT[name] == true`.
profiles.CURRENT = { [profiles.PC] = true, [profiles.BATTERY] = true }
for _, name in pairs(profiles.VARIANTS) do
  profiles.CURRENT[name] = true
end
for _, name in pairs(profiles.BATTERY_VARIANTS) do
  profiles.CURRENT[name] = true
end

-- Every profile name this driver has ever shipped, oldest first. A name that
-- is not in here belongs to another driver, or to a version newer than this
-- one, and is left alone. #107: the ten v1 names (the default and the nine
-- icon variants of #100), then twenty names per later generation (every style
-- with and without the battery, #116): v2 to v6 and the twenty current ones.
profiles.KNOWN = {}
for _, style in ipairs(profiles.STYLES) do
  profiles.KNOWN[#profiles.KNOWN + 1] = profiles.name_for(style, false, 1)
end
for version = 2, profiles.VERSION do
  for _, battery in ipairs({ false, true }) do
    for _, style in ipairs(profiles.STYLES) do
      profiles.KNOWN[#profiles.KNOWN + 1] = profiles.name_for(style, battery, version)
    end
  end
end

-- Generations that only ever lived on the Dev channel. Their names stay in
-- KNOWN so a development device still on one migrates, but their files are
-- not packaged: the package limit is 655360 bytes.
profiles.UNSHIPPED_VERSIONS = { [2] = true, [3] = true, [4] = true, [5] = true, [6] = true }

--- True when the package carries a file for this profile name.
function profiles.is_shipped(name)
  local version = tonumber(tostring(name or ""):match("%.v(%d+)$"))
  return version ~= nil and not profiles.UNSHIPPED_VERSIONS[version]
end

-- What a device with neither a name nor `fields.PROFILE_NAME` is assumed to be
-- on: the oldest name this driver ever created a device with.
profiles.LEGACY = "pc.v1"

-- This driver creates no child device any more. Two kinds may be left on a
-- development hub, neither with a profile in the package, and both are
-- deleted (`remove_child`): #81's display child (`pc-display.vN`, key
-- "display") and #123's app children (`pc-app.v1`, keyed by process name),
-- which the watch card's slots replaced before anything was published.
profiles.CHILD_PREFIXES = { "pc-display", "pc-app." }

local function logger()
  local ok, log = pcall(require, "log")
  if ok then
    return log
  end
  local noop = function() end
  return { trace = noop, debug = noop, info = noop, warn = noop, error = noop }
end

--------------------------------------------------------------------------------
-- pure
--------------------------------------------------------------------------------

--- The profile a device is created with now.
function profiles.current()
  return profiles.PC
end

--- Every profile name this driver has shipped.
function profiles.known()
  return profiles.KNOWN
end

--- #100: true when `name` is one of the profiles a device is created on or
--- switched between now - `PC` or any variant, with or without the battery.
function profiles.is_current(name)
  if type(name) ~= "string" or name == "" then
    return false
  end
  return name == profiles.PC or profiles.CURRENT[name] == true
end

--- #100/#116: the profile an `iconStyle` value asks for, with or without the
--- battery component. Anything that is not a known style (nil, a typo, a value
--- a newer driver added) is the default.
function profiles.for_style(style, battery)
  if battery == true then
    return profiles.BATTERY_VARIANTS[style] or profiles.BATTERY
  end
  return profiles.VARIANTS[style] or profiles.PC
end

--- #100: the `iconStyle` a current profile name stands for, or nil for a name
--- that is not current (older, foreign, or none).
function profiles.style_of(name)
  if type(name) ~= "string" then
    return nil
  end
  if name == profiles.PC or name == profiles.BATTERY then
    return profiles.DEFAULT_STYLE
  end
  for style, variant in pairs(profiles.VARIANTS) do
    if variant == name or profiles.BATTERY_VARIANTS[style] == name then
      return style
    end
  end
  return nil
end

--- #116: true when a current profile name is one of the battery variants,
--- false for the plain ones, nil for a name that is not current.
function profiles.battery_of(name)
  if not profiles.is_current(name) then
    return nil
  end
  return name:match("%-battery%.v%d+$") ~= nil
end

--- The style an OLDER name of this driver carried: `pc-<style>[-battery].vN`
--- with a style that still exists, else the default. Pure pattern reading,
--- because a superseded name is by definition no longer in `VARIANTS`.
local function style_in_name(name)
  local base = name:gsub("%-battery(%.v%d+)$", "%1")
  local style = base:match("^pc%-(%a+)%.v%d+$")
  if style and profiles.VARIANTS[style] then
    return style
  end
  return profiles.DEFAULT_STYLE
end

--- The profile `device_profile_name` has to move to, or nil.
--
-- nil covers all three "do nothing" cases: already current (any variant,
-- #100), not a name this driver ever used (foreign device, or a version from
-- the future), and no name at all. A child profile name is not ours to
-- migrate either: no such series is packaged any more, and such a device is deleted
-- instead (`is_child`). A known older name keeps its style, and a
-- `-battery` name (v2 on) keeps its battery half.
-- @param battery #107: whether the target is the battery variant. The v1 names
--   never had one, so the caller says, and "no" until a status has said
--   otherwise. A v2 `-battery` name already says "yes" and goes to a battery
--   profile whatever the caller passes: the device got there on two statuses
--   that agreed (#116), which is better evidence than a field a single odd
--   status may not have written.
function profiles.migration_for(device_profile_name, battery)
  if type(device_profile_name) ~= "string" or device_profile_name == "" then
    return nil
  end
  if profiles.is_current(device_profile_name) then
    return nil
  end
  for _, known in ipairs(profiles.known()) do
    if device_profile_name == known then
      local on_battery = battery == true
        or device_profile_name:match("%-battery%.v%d+$") ~= nil
      return profiles.for_style(style_in_name(device_profile_name), on_battery)
    end
  end
  return nil
end


--- True when `name` is the profile of a child device an older build created
--- (`CHILD_PREFIXES`).
function profiles.is_child_profile(name)
  if type(name) ~= "string" then
    return false
  end
  for _, prefix in ipairs(profiles.CHILD_PREFIXES) do
    if name:sub(1, #prefix) == prefix then
      return true
    end
  end
  return false
end

--- True when `device` is a leftover child device (see `CHILD_PREFIXES`).
--
-- Two independent marks, because a hub may only carry one of them: a
-- `parent_assigned_child_key` (only an EDGE_CHILD has one, and this driver
-- creates none any more), and a profile name from a child series.
function profiles.is_child(device)
  if type(device) ~= "table" then
    return false
  end
  local key = device.parent_assigned_child_key
  if type(key) == "string" and key ~= "" then
    return true
  end
  return profiles.is_child_profile(profiles.name_of(device))
end

--------------------------------------------------------------------------------
-- reading the name off a device
--------------------------------------------------------------------------------

local function stored_name(device)
  if type(device) ~= "table" or type(device.get_field) ~= "function" then
    return nil
  end
  local value = fields.get(device, fields.PROFILE_NAME)
  if type(value) == "string" and value ~= "" then
    return value
  end
  return nil
end

--- The profile name of `device`.
--
-- The Edge API exposes `device.profile` as a table of `id` and `components`;
-- the *name* is there on some firmwares only, so it wins when present and the
-- field written at creation time (and after every migration) is the fallback.
-- A device with neither predates #79 and is therefore on v1.
function profiles.name_of(device)
  local profile = (device or {}).profile
  if type(profile) == "table" and type(profile.name) == "string" and profile.name ~= "" then
    return profile.name
  end
  if type(profile) == "string" and profile ~= "" then
    return profile
  end
  return stored_name(device) or profiles.LEGACY
end

--------------------------------------------------------------------------------
-- driver glue
--------------------------------------------------------------------------------

--- Record that `device` is on the current profile, so the next driver version
--- can tell which version it has to move it from.
function profiles.remember(device, name)
  if type(device) ~= "table" or type(device.set_field) ~= "function" then
    return nil
  end
  name = name or profiles.current()
  fields.set(device, fields.PROFILE_NAME, name)
  return name
end

-- Devices this driver run has already looked at. One attempt per device per
-- driver lifetime: `added` and `init` both call `ensure`, and a hub that
-- refuses the update must not be asked again in a loop.
local attempted = {}

-- #100: the loop guard of `apply_style`, two maps per driver run.
--
-- `switched` is the profile this run last moved each device to. It stands in
-- for `name_of` afterwards: the switch itself fires `infoChanged` again, and on
-- a hub that is slow to (or never does) put the new name on `device.profile`,
-- `name_of` would still read the old one and ask for the same switch again,
-- and again. #107: `ensure` writes it too.
--
-- `refused` is the target the hub last turned down. The same preference is
-- not asked for twice in one run; a different value, or the next driver start,
-- asks again.
local switched = {}
local refused = {}

local function attempt_key(device)
  local id = device.id
  if type(id) == "string" and id ~= "" then
    return id
  end
  return device
end

--- The profile name this driver run believes `device` is on: the one it last
--- moved it to, else what the device says (`name_of`).
function profiles.current_name(device)
  if type(device) ~= "table" then
    return nil
  end
  return switched[attempt_key(device)] or profiles.name_of(device)
end

--- Move `device` onto the current profile if it is due (§6.6).
--
-- Returns the new profile name, or nil when nothing was done. Called from
-- `init` and `added`; only the first call per device does anything.
function profiles.ensure(device)
  if type(device) ~= "table" then
    return nil
  end
  local key = attempt_key(device)
  if attempted[key] then
    return nil
  end
  attempted[key] = true

  local name = profiles.name_of(device)
  -- #107: a v1 device lands on the current profile of its style. Whether it
  -- has a battery is only known once a status has said so (#116:
  -- `fields.HAS_BATTERY`, which a v1 device never wrote), so it lands on the plain
  -- one and the first statuses move a laptop on (`apply_battery`). A v2 device
  -- keeps its battery half (`migration_for`).
  local target = profiles.migration_for(name, profiles.has_battery(device))
  if not target then
    -- Nothing to do, but keep the field in step with reality when the device
    -- is already on a current profile (the default or a variant, #100).
    if profiles.is_current(name) then
      profiles.remember(device, name)
    end
    return nil
  end

  local ok, err = pcall(function()
    return device:try_update_metadata({ profile = target })
  end)
  if not ok then
    logger().warn(string.format("could not migrate %s to %s: %s",
      tostring(device.id), target, tostring(err)))
    return nil
  end
  profiles.remember(device, target)
  -- #107: from here on this run reads the new name, whatever the hub still
  -- reports on `device.profile` - an icon switch right after a migration must
  -- start from the new name, not from the old one it would refuse to touch.
  switched[key] = target
  logger().info(string.format("migrated %s to %s", tostring(device.id), target))
  return target
end

--- #100: move `device` onto the profile its `iconStyle` preference asks for.
--
-- Returns the new profile name, or nil when nothing was done. Called from
-- `infoChanged` (the user changed the preference) and from `init` (the driver
-- restarted between the preference changing and the switch landing).
--
-- Left alone: a device with no `iconStyle` at all (the preferences have not
-- arrived - it is not a request for the default), and a device that is not on
-- a current profile (foreign, or an older version that `ensure` moves first).
-- At most one `try_update_metadata` per device and target per driver run.
function profiles.apply_style(device)
  if type(device) ~= "table" then
    return nil
  end
  local style = (device.preferences or {}).iconStyle
  if style == nil then
    return nil
  end
  local key = attempt_key(device)
  local name = profiles.current_name(device)
  if not profiles.is_current(name) then
    return nil
  end
  -- #107: the icon changes, the battery component stays where it is.
  local target = profiles.for_style(style, profiles.battery_of(name))
  if name == target or refused[key] == target then
    return nil
  end

  local ok, err = pcall(function()
    return device:try_update_metadata({ profile = target })
  end)
  if not ok then
    refused[key] = target
    logger().warn(string.format("could not switch %s to %s: %s",
      tostring(device.id), target, tostring(err)))
    return nil
  end
  switched[key] = target
  refused[key] = nil
  profiles.remember(device, target)
  logger().info(string.format("switched %s from %s to %s (iconStyle %s)",
    tostring(device.id), name, target, tostring(style)))
  return target
end

-- #116: consecutive statuses that disagreed with the device's profile about
-- the battery, per device: `{ present = bool, count = n }`.
local battery_votes = {}

-- #116: how many statuses in a row have to say the same thing before the
-- device changes profile. One odd reading (a flaky `GetSystemPowerStatus`, a
-- service that restarted into its "no battery yet" placeholder) must not cost
-- the user a profile switch and a repaint each way.
profiles.BATTERY_VOTES = 2

--- #116: whether the last settled status said this PC has a battery (the
--- persisted `fields.HAS_BATTERY`), false when none has.
function profiles.has_battery(device)
  return fields.get(device, fields.HAS_BATTERY) == true
end

local function remember_battery(device, present)
  if profiles.has_battery(device) ~= present then
    fields.set(device, fields.HAS_BATTERY, present)
  end
end

--- #116: move `device` between the plain and the `-battery` profile of its
--- style when the status disagrees with the one it is on.
--
-- Returns the new profile name, or nil when nothing was done. Called after
-- every status (poll and push) with `status.battery.present`. Only after
-- `BATTERY_VOTES` consecutive statuses agree on the other answer does it ask
-- for the switch - one each way at most per real change. The style is the one
-- the current name carries (`iconStyle` is `apply_style`'s business), and a
-- device that is not on a current profile is left to `ensure`. The answer is
-- persisted (`fields.HAS_BATTERY`) so the next migration lands on the right side.
function profiles.apply_battery(device, present)
  if type(device) ~= "table" then
    return nil
  end
  present = present == true
  local key = attempt_key(device)
  local name = profiles.current_name(device)
  local on_battery = profiles.battery_of(name)
  if on_battery == nil then
    battery_votes[key] = nil
    return nil
  end
  if on_battery == present then
    battery_votes[key] = nil
    remember_battery(device, present)
    return nil
  end
  local votes = battery_votes[key]
  if votes and votes.present == present then
    votes.count = votes.count + 1
  else
    votes = { present = present, count = 1 }
    battery_votes[key] = votes
  end
  if votes.count < profiles.BATTERY_VOTES then
    return nil
  end
  local target = profiles.for_style(profiles.style_of(name), present)
  if refused[key] == target then
    return nil
  end
  local ok, err = pcall(function()
    return device:try_update_metadata({ profile = target })
  end)
  if not ok then
    refused[key] = target
    logger().warn(string.format("could not switch %s to %s: %s",
      tostring(device.id), target, tostring(err)))
    return nil
  end
  battery_votes[key] = nil
  switched[key] = target
  refused[key] = nil
  profiles.remember(device, target)
  remember_battery(device, present)
  logger().info(string.format("switched %s from %s to %s (battery %s)",
    tostring(device.id), name, target, present and "present" or "absent"))
  return target
end

-- Devices this driver run has already tried to delete, for the same reason
-- `attempted` exists: `init` fires more than once per device, and every PC's
-- `init` walks the device list.
local removed = {}

--- Delete one leftover child (`is_child`), once per device per driver run.
--
-- Returns true when the delete was asked for now. `driver:try_delete_device`
-- is the API (lua_libs st/driver.lua; there is no device method); it answers
-- `nil, "<why>"` on a hub without the feature and may raise. A failure is
-- logged once and the child stays - it does nothing any more (its lifecycle
-- is ignored, nothing is emitted on it), and the user can delete it in the app.
function profiles.remove_child(driver, device)
  if not profiles.is_child(device) then
    return false
  end
  local key = attempt_key(device)
  if removed[key] then
    return false
  end
  removed[key] = true

  local what = tostring(device.parent_assigned_child_key or profiles.name_of(device))
  logger().info(string.format("removing leftover child %s (%s)", tostring(device.id), what))
  local ok, result, why = pcall(function() return driver:try_delete_device(device.id) end)
  if not ok or (result == nil and why ~= nil) then
    logger().warn(string.format("could not delete leftover child %s (%s): %s",
      tostring(device.id), what, tostring(ok and why or result)))
  end
  return true
end

--- Delete every leftover child among the driver's devices (`remove_child`).
--- Called from a PC's `init` and `added`. Returns how many were asked for.
function profiles.remove_children(driver)
  local ok, devices = pcall(function() return driver:get_devices() end)
  if not ok or type(devices) ~= "table" then
    return 0
  end
  local count = 0
  for _, device in ipairs(devices) do
    if profiles.remove_child(driver, device) then
      count = count + 1
    end
  end
  return count
end

--- Forget the one-attempt-per-device guards (tests only).
function profiles.reset()
  attempted = {}
  removed = {}
  switched = {}
  refused = {}
  battery_votes = {}
end

return profiles
